---
title: "Lab 03 - Nobel laureates"
author: "Zi Li"
date: "Jan 29"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{r}
as_tibble(nobel) 
glimpse(nobel)

nobel_living <- nobel %>%
  filter(!is.na(country))%>%  
           filter (gender != "org") %>%   
           filter (is.na(died_date))

glimpse(nobel_living)

# I found a useful answer for how to use filter commends on "stackoverflow"
```

# answer for Ex 1.1: we have 935 observations and 26 variables in this dataset; observations represented by rows and variables represented by collums. 
# answer for Ex 1.2:  my nobel_living left with a data frame with 228 observations and 27 variables. 

### Exercise 2

```{r}
nobel_living <- nobel_living %>%
  mutate(country_us = if_else(country == "USA", "USA", "Other")
  )

nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

```

### Exercise 3

```{r}

## Create a faceted bar plot visualizing the relationship between the category of prize and whether the laureate was in the US when they won the nobel prize.

library(ggplot2) 
ggplot(
  data = nobel_living_science,
  mapping = aes (
    x = country_us, fill = country_us)) + geom_bar() + coord_flip() + facet_wrap(vars(category))

# I found some useful examples on Source: R/facet-wrap.R. 
```

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...
